import {
  Activity,
  AlertCircle,
  Bell,
  BellOff,
  Bold,
  Bot,
  BriefcaseBusiness,
  Building2,
  Calendar,
  Check,
  ChevronRight,
  CircleDollarSign,
  ClipboardCheck,
  Download,
  Edit3,
  FileText,
  Flag,
  Handshake,
  History,
  Home,
  Inbox,
  Italic,
  KanbanSquare,
  LayoutDashboard,
  Lightbulb,
  Mail,
  MessageCircle,
  MoreVertical,
  Paperclip,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Star,
  StickyNote,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  Users,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const icons: Record<string, LucideIcon> = {
  account_tree: KanbanSquare,
  add: Plus,
  analytics: Activity,
  attach_file: Paperclip,
  bolt: Zap,
  business: Building2,
  call: BriefcaseBusiness,
  chat: MessageCircle,
  chat_bubble: MessageCircle,
  chevron_right: ChevronRight,
  close: X,
  contacts: Users,
  conversion_path: Target,
  corporate_fare: Building2,
  dashboard: LayoutDashboard,
  delete: Trash2,
  description: FileText,
  domain: Building2,
  donut_large: CircleDollarSign,
  edit_note: Edit3,
  emoji_events: Trophy,
  error: AlertCircle,
  event: Calendar,
  filter_alt: SlidersHorizontal,
  flag: Flag,
  format_bold: Bold,
  format_italic: Italic,
  groups: Users,
  handshake: Handshake,
  history: History,
  inbox: Inbox,
  ios_share: Download,
  lightbulb: Lightbulb,
  logout: X,
  mail: Mail,
  manage_history: History,
  more_vert: MoreVertical,
  notifications: Bell,
  notifications_off: BellOff,
  open_in_new: Send,
  person_add: Users,
  person_search: Search,
  refresh: RefreshCw,
  settings: Settings,
  slideshow: Sparkles,
  stars: Sparkles,
  sticky_note_2: StickyNote,
  task_alt: ClipboardCheck,
  tune: SlidersHorizontal,
  upload_file: Upload,
  view_kanban: KanbanSquare,
  workspace_premium: Trophy,
};

interface IconProps {
  name: string;
  className?: string;
  title?: string;
}

export function Icon({ name, className, title }: IconProps) {
  const Lucide = icons[name] ?? Bot;
  return <Lucide aria-hidden={!title} aria-label={title} className={cn("h-5 w-5", className)} />;
}
