/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicLeadsCaptureSubmitRouteImport } from './routes/api/public/leads-capture-submit'
import { Route as ApiPublicLeadsCaptureRouteImport } from './routes/api.public.leads-capture'
import { Route as AuthenticatedAppTasksIndexRouteImport } from './routes/_authenticated/app.tasks.index'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/app.settings.index'
import { Route as AuthenticatedAppQuotesIndexRouteImport } from './routes/_authenticated/app.quotes.index'
import { Route as AuthenticatedAppPipelineIndexRouteImport } from './routes/_authenticated/app.pipeline.index'
import { Route as AuthenticatedAppLeadsIndexRouteImport } from './routes/_authenticated/app.leads.index'
import { Route as AuthenticatedAppInvoicesIndexRouteImport } from './routes/_authenticated/app.invoices.index'
import { Route as AuthenticatedAppDealsIndexRouteImport } from './routes/_authenticated/app.deals.index'
import { Route as AuthenticatedAppContactsIndexRouteImport } from './routes/_authenticated/app.contacts.index'
import { Route as AuthenticatedAppCompaniesIndexRouteImport } from './routes/_authenticated/app.companies.index'
import { Route as AuthenticatedAppAnalyticsIndexRouteImport } from './routes/_authenticated/app.analytics.index'
import { Route as AuthenticatedAppActivitiesIndexRouteImport } from './routes/_authenticated/app.activities.index'
import { Route as AuthenticatedAppQuotesCatalogRouteImport } from './routes/_authenticated/app.quotes.catalog'
import { Route as AuthenticatedAppQuotesIdRouteImport } from './routes/_authenticated/app.quotes.$id'
import { Route as AuthenticatedAppLeadsIdRouteImport } from './routes/_authenticated/app.leads.$id'
import { Route as AuthenticatedAppInvoicesIdRouteImport } from './routes/_authenticated/app.invoices.$id'
import { Route as AuthenticatedAppDealsIdRouteImport } from './routes/_authenticated/app.deals.$id'
import { Route as AuthenticatedAppContactsIdRouteImport } from './routes/_authenticated/app.contacts.$id'
import { Route as AuthenticatedAppCompaniesIdRouteImport } from './routes/_authenticated/app.companies.$id'
import { Route as AuthenticatedAppAnalyticsRepIdRouteImport } from './routes/_authenticated/app.analytics.$repId'
import { Route as AuthenticatedAppQuotesPrintIdRouteImport } from './routes/_authenticated/app.quotes.print.$id'
import { Route as AuthenticatedAppInvoicesPrintIdRouteImport } from './routes/_authenticated/app.invoices.print.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicLeadsCaptureSubmitRoute =
  ApiPublicLeadsCaptureSubmitRouteImport.update({
    id: '/api/public/leads-capture-submit',
    path: '/api/public/leads-capture-submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsCaptureRoute = ApiPublicLeadsCaptureRouteImport.update({
  id: '/api/public/leads-capture',
  path: '/api/public/leads-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppTasksIndexRoute =
  AuthenticatedAppTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuotesIndexRoute =
  AuthenticatedAppQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPipelineIndexRoute =
  AuthenticatedAppPipelineIndexRouteImport.update({
    id: '/pipeline/',
    path: '/pipeline/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsIndexRoute =
  AuthenticatedAppLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInvoicesIndexRoute =
  AuthenticatedAppInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDealsIndexRoute =
  AuthenticatedAppDealsIndexRouteImport.update({
    id: '/deals/',
    path: '/deals/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContactsIndexRoute =
  AuthenticatedAppContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompaniesIndexRoute =
  AuthenticatedAppCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAnalyticsIndexRoute =
  AuthenticatedAppAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppActivitiesIndexRoute =
  AuthenticatedAppActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuotesCatalogRoute =
  AuthenticatedAppQuotesCatalogRouteImport.update({
    id: '/quotes/catalog',
    path: '/quotes/catalog',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuotesIdRoute =
  AuthenticatedAppQuotesIdRouteImport.update({
    id: '/quotes/$id',
    path: '/quotes/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsIdRoute = AuthenticatedAppLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInvoicesIdRoute =
  AuthenticatedAppInvoicesIdRouteImport.update({
    id: '/invoices/$id',
    path: '/invoices/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDealsIdRoute = AuthenticatedAppDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppContactsIdRoute =
  AuthenticatedAppContactsIdRouteImport.update({
    id: '/contacts/$id',
    path: '/contacts/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompaniesIdRoute =
  AuthenticatedAppCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAnalyticsRepIdRoute =
  AuthenticatedAppAnalyticsRepIdRouteImport.update({
    id: '/analytics/$repId',
    path: '/analytics/$repId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuotesPrintIdRoute =
  AuthenticatedAppQuotesPrintIdRouteImport.update({
    id: '/quotes/print/$id',
    path: '/quotes/print/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInvoicesPrintIdRoute =
  AuthenticatedAppInvoicesPrintIdRouteImport.update({
    id: '/invoices/print/$id',
    path: '/invoices/print/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mfa': typeof MfaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/public/leads-capture': typeof ApiPublicLeadsCaptureRoute
  '/api/public/leads-capture-submit': typeof ApiPublicLeadsCaptureSubmitRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/analytics/$repId': typeof AuthenticatedAppAnalyticsRepIdRoute
  '/app/companies/$id': typeof AuthenticatedAppCompaniesIdRoute
  '/app/contacts/$id': typeof AuthenticatedAppContactsIdRoute
  '/app/deals/$id': typeof AuthenticatedAppDealsIdRoute
  '/app/invoices/$id': typeof AuthenticatedAppInvoicesIdRoute
  '/app/leads/$id': typeof AuthenticatedAppLeadsIdRoute
  '/app/quotes/$id': typeof AuthenticatedAppQuotesIdRoute
  '/app/quotes/catalog': typeof AuthenticatedAppQuotesCatalogRoute
  '/app/activities/': typeof AuthenticatedAppActivitiesIndexRoute
  '/app/analytics/': typeof AuthenticatedAppAnalyticsIndexRoute
  '/app/companies/': typeof AuthenticatedAppCompaniesIndexRoute
  '/app/contacts/': typeof AuthenticatedAppContactsIndexRoute
  '/app/deals/': typeof AuthenticatedAppDealsIndexRoute
  '/app/invoices/': typeof AuthenticatedAppInvoicesIndexRoute
  '/app/leads/': typeof AuthenticatedAppLeadsIndexRoute
  '/app/pipeline/': typeof AuthenticatedAppPipelineIndexRoute
  '/app/quotes/': typeof AuthenticatedAppQuotesIndexRoute
  '/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
  '/app/invoices/print/$id': typeof AuthenticatedAppInvoicesPrintIdRoute
  '/app/quotes/print/$id': typeof AuthenticatedAppQuotesPrintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mfa': typeof MfaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/leads-capture': typeof ApiPublicLeadsCaptureRoute
  '/api/public/leads-capture-submit': typeof ApiPublicLeadsCaptureSubmitRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/analytics/$repId': typeof AuthenticatedAppAnalyticsRepIdRoute
  '/app/companies/$id': typeof AuthenticatedAppCompaniesIdRoute
  '/app/contacts/$id': typeof AuthenticatedAppContactsIdRoute
  '/app/deals/$id': typeof AuthenticatedAppDealsIdRoute
  '/app/invoices/$id': typeof AuthenticatedAppInvoicesIdRoute
  '/app/leads/$id': typeof AuthenticatedAppLeadsIdRoute
  '/app/quotes/$id': typeof AuthenticatedAppQuotesIdRoute
  '/app/quotes/catalog': typeof AuthenticatedAppQuotesCatalogRoute
  '/app/activities': typeof AuthenticatedAppActivitiesIndexRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsIndexRoute
  '/app/companies': typeof AuthenticatedAppCompaniesIndexRoute
  '/app/contacts': typeof AuthenticatedAppContactsIndexRoute
  '/app/deals': typeof AuthenticatedAppDealsIndexRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesIndexRoute
  '/app/leads': typeof AuthenticatedAppLeadsIndexRoute
  '/app/pipeline': typeof AuthenticatedAppPipelineIndexRoute
  '/app/quotes': typeof AuthenticatedAppQuotesIndexRoute
  '/app/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/app/tasks': typeof AuthenticatedAppTasksIndexRoute
  '/app/invoices/print/$id': typeof AuthenticatedAppInvoicesPrintIdRoute
  '/app/quotes/print/$id': typeof AuthenticatedAppQuotesPrintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mfa': typeof MfaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/public/leads-capture': typeof ApiPublicLeadsCaptureRoute
  '/api/public/leads-capture-submit': typeof ApiPublicLeadsCaptureSubmitRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/analytics/$repId': typeof AuthenticatedAppAnalyticsRepIdRoute
  '/_authenticated/app/companies/$id': typeof AuthenticatedAppCompaniesIdRoute
  '/_authenticated/app/contacts/$id': typeof AuthenticatedAppContactsIdRoute
  '/_authenticated/app/deals/$id': typeof AuthenticatedAppDealsIdRoute
  '/_authenticated/app/invoices/$id': typeof AuthenticatedAppInvoicesIdRoute
  '/_authenticated/app/leads/$id': typeof AuthenticatedAppLeadsIdRoute
  '/_authenticated/app/quotes/$id': typeof AuthenticatedAppQuotesIdRoute
  '/_authenticated/app/quotes/catalog': typeof AuthenticatedAppQuotesCatalogRoute
  '/_authenticated/app/activities/': typeof AuthenticatedAppActivitiesIndexRoute
  '/_authenticated/app/analytics/': typeof AuthenticatedAppAnalyticsIndexRoute
  '/_authenticated/app/companies/': typeof AuthenticatedAppCompaniesIndexRoute
  '/_authenticated/app/contacts/': typeof AuthenticatedAppContactsIndexRoute
  '/_authenticated/app/deals/': typeof AuthenticatedAppDealsIndexRoute
  '/_authenticated/app/invoices/': typeof AuthenticatedAppInvoicesIndexRoute
  '/_authenticated/app/leads/': typeof AuthenticatedAppLeadsIndexRoute
  '/_authenticated/app/pipeline/': typeof AuthenticatedAppPipelineIndexRoute
  '/_authenticated/app/quotes/': typeof AuthenticatedAppQuotesIndexRoute
  '/_authenticated/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
  '/_authenticated/app/invoices/print/$id': typeof AuthenticatedAppInvoicesPrintIdRoute
  '/_authenticated/app/quotes/print/$id': typeof AuthenticatedAppQuotesPrintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mfa'
    | '/reset-password'
    | '/app'
    | '/api/public/leads-capture'
    | '/api/public/leads-capture-submit'
    | '/app/'
    | '/app/analytics/$repId'
    | '/app/companies/$id'
    | '/app/contacts/$id'
    | '/app/deals/$id'
    | '/app/invoices/$id'
    | '/app/leads/$id'
    | '/app/quotes/$id'
    | '/app/quotes/catalog'
    | '/app/activities/'
    | '/app/analytics/'
    | '/app/companies/'
    | '/app/contacts/'
    | '/app/deals/'
    | '/app/invoices/'
    | '/app/leads/'
    | '/app/pipeline/'
    | '/app/quotes/'
    | '/app/settings/'
    | '/app/tasks/'
    | '/app/invoices/print/$id'
    | '/app/quotes/print/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mfa'
    | '/reset-password'
    | '/api/public/leads-capture'
    | '/api/public/leads-capture-submit'
    | '/app'
    | '/app/analytics/$repId'
    | '/app/companies/$id'
    | '/app/contacts/$id'
    | '/app/deals/$id'
    | '/app/invoices/$id'
    | '/app/leads/$id'
    | '/app/quotes/$id'
    | '/app/quotes/catalog'
    | '/app/activities'
    | '/app/analytics'
    | '/app/companies'
    | '/app/contacts'
    | '/app/deals'
    | '/app/invoices'
    | '/app/leads'
    | '/app/pipeline'
    | '/app/quotes'
    | '/app/settings'
    | '/app/tasks'
    | '/app/invoices/print/$id'
    | '/app/quotes/print/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mfa'
    | '/reset-password'
    | '/_authenticated/app'
    | '/api/public/leads-capture'
    | '/api/public/leads-capture-submit'
    | '/_authenticated/app/'
    | '/_authenticated/app/analytics/$repId'
    | '/_authenticated/app/companies/$id'
    | '/_authenticated/app/contacts/$id'
    | '/_authenticated/app/deals/$id'
    | '/_authenticated/app/invoices/$id'
    | '/_authenticated/app/leads/$id'
    | '/_authenticated/app/quotes/$id'
    | '/_authenticated/app/quotes/catalog'
    | '/_authenticated/app/activities/'
    | '/_authenticated/app/analytics/'
    | '/_authenticated/app/companies/'
    | '/_authenticated/app/contacts/'
    | '/_authenticated/app/deals/'
    | '/_authenticated/app/invoices/'
    | '/_authenticated/app/leads/'
    | '/_authenticated/app/pipeline/'
    | '/_authenticated/app/quotes/'
    | '/_authenticated/app/settings/'
    | '/_authenticated/app/tasks/'
    | '/_authenticated/app/invoices/print/$id'
    | '/_authenticated/app/quotes/print/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MfaRoute: typeof MfaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicLeadsCaptureRoute: typeof ApiPublicLeadsCaptureRoute
  ApiPublicLeadsCaptureSubmitRoute: typeof ApiPublicLeadsCaptureSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/leads-capture-submit': {
      id: '/api/public/leads-capture-submit'
      path: '/api/public/leads-capture-submit'
      fullPath: '/api/public/leads-capture-submit'
      preLoaderRoute: typeof ApiPublicLeadsCaptureSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads-capture': {
      id: '/api/public/leads-capture'
      path: '/api/public/leads-capture'
      fullPath: '/api/public/leads-capture'
      preLoaderRoute: typeof ApiPublicLeadsCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/tasks/': {
      id: '/_authenticated/app/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AuthenticatedAppTasksIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/': {
      id: '/_authenticated/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotes/': {
      id: '/_authenticated/app/quotes/'
      path: '/quotes'
      fullPath: '/app/quotes/'
      preLoaderRoute: typeof AuthenticatedAppQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pipeline/': {
      id: '/_authenticated/app/pipeline/'
      path: '/pipeline'
      fullPath: '/app/pipeline/'
      preLoaderRoute: typeof AuthenticatedAppPipelineIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads/': {
      id: '/_authenticated/app/leads/'
      path: '/leads'
      fullPath: '/app/leads/'
      preLoaderRoute: typeof AuthenticatedAppLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invoices/': {
      id: '/_authenticated/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AuthenticatedAppInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deals/': {
      id: '/_authenticated/app/deals/'
      path: '/deals'
      fullPath: '/app/deals/'
      preLoaderRoute: typeof AuthenticatedAppDealsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacts/': {
      id: '/_authenticated/app/contacts/'
      path: '/contacts'
      fullPath: '/app/contacts/'
      preLoaderRoute: typeof AuthenticatedAppContactsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/companies/': {
      id: '/_authenticated/app/companies/'
      path: '/companies'
      fullPath: '/app/companies/'
      preLoaderRoute: typeof AuthenticatedAppCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics/': {
      id: '/_authenticated/app/analytics/'
      path: '/analytics'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/activities/': {
      id: '/_authenticated/app/activities/'
      path: '/activities'
      fullPath: '/app/activities/'
      preLoaderRoute: typeof AuthenticatedAppActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotes/catalog': {
      id: '/_authenticated/app/quotes/catalog'
      path: '/quotes/catalog'
      fullPath: '/app/quotes/catalog'
      preLoaderRoute: typeof AuthenticatedAppQuotesCatalogRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotes/$id': {
      id: '/_authenticated/app/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/app/quotes/$id'
      preLoaderRoute: typeof AuthenticatedAppQuotesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads/$id': {
      id: '/_authenticated/app/leads/$id'
      path: '/leads/$id'
      fullPath: '/app/leads/$id'
      preLoaderRoute: typeof AuthenticatedAppLeadsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invoices/$id': {
      id: '/_authenticated/app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/app/invoices/$id'
      preLoaderRoute: typeof AuthenticatedAppInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deals/$id': {
      id: '/_authenticated/app/deals/$id'
      path: '/deals/$id'
      fullPath: '/app/deals/$id'
      preLoaderRoute: typeof AuthenticatedAppDealsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacts/$id': {
      id: '/_authenticated/app/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/app/contacts/$id'
      preLoaderRoute: typeof AuthenticatedAppContactsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/companies/$id': {
      id: '/_authenticated/app/companies/$id'
      path: '/companies/$id'
      fullPath: '/app/companies/$id'
      preLoaderRoute: typeof AuthenticatedAppCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics/$repId': {
      id: '/_authenticated/app/analytics/$repId'
      path: '/analytics/$repId'
      fullPath: '/app/analytics/$repId'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRepIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotes/print/$id': {
      id: '/_authenticated/app/quotes/print/$id'
      path: '/quotes/print/$id'
      fullPath: '/app/quotes/print/$id'
      preLoaderRoute: typeof AuthenticatedAppQuotesPrintIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invoices/print/$id': {
      id: '/_authenticated/app/invoices/print/$id'
      path: '/invoices/print/$id'
      fullPath: '/app/invoices/print/$id'
      preLoaderRoute: typeof AuthenticatedAppInvoicesPrintIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAnalyticsRepIdRoute: typeof AuthenticatedAppAnalyticsRepIdRoute
  AuthenticatedAppCompaniesIdRoute: typeof AuthenticatedAppCompaniesIdRoute
  AuthenticatedAppContactsIdRoute: typeof AuthenticatedAppContactsIdRoute
  AuthenticatedAppDealsIdRoute: typeof AuthenticatedAppDealsIdRoute
  AuthenticatedAppInvoicesIdRoute: typeof AuthenticatedAppInvoicesIdRoute
  AuthenticatedAppLeadsIdRoute: typeof AuthenticatedAppLeadsIdRoute
  AuthenticatedAppQuotesIdRoute: typeof AuthenticatedAppQuotesIdRoute
  AuthenticatedAppQuotesCatalogRoute: typeof AuthenticatedAppQuotesCatalogRoute
  AuthenticatedAppActivitiesIndexRoute: typeof AuthenticatedAppActivitiesIndexRoute
  AuthenticatedAppAnalyticsIndexRoute: typeof AuthenticatedAppAnalyticsIndexRoute
  AuthenticatedAppCompaniesIndexRoute: typeof AuthenticatedAppCompaniesIndexRoute
  AuthenticatedAppContactsIndexRoute: typeof AuthenticatedAppContactsIndexRoute
  AuthenticatedAppDealsIndexRoute: typeof AuthenticatedAppDealsIndexRoute
  AuthenticatedAppInvoicesIndexRoute: typeof AuthenticatedAppInvoicesIndexRoute
  AuthenticatedAppLeadsIndexRoute: typeof AuthenticatedAppLeadsIndexRoute
  AuthenticatedAppPipelineIndexRoute: typeof AuthenticatedAppPipelineIndexRoute
  AuthenticatedAppQuotesIndexRoute: typeof AuthenticatedAppQuotesIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppTasksIndexRoute: typeof AuthenticatedAppTasksIndexRoute
  AuthenticatedAppInvoicesPrintIdRoute: typeof AuthenticatedAppInvoicesPrintIdRoute
  AuthenticatedAppQuotesPrintIdRoute: typeof AuthenticatedAppQuotesPrintIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAnalyticsRepIdRoute: AuthenticatedAppAnalyticsRepIdRoute,
  AuthenticatedAppCompaniesIdRoute: AuthenticatedAppCompaniesIdRoute,
  AuthenticatedAppContactsIdRoute: AuthenticatedAppContactsIdRoute,
  AuthenticatedAppDealsIdRoute: AuthenticatedAppDealsIdRoute,
  AuthenticatedAppInvoicesIdRoute: AuthenticatedAppInvoicesIdRoute,
  AuthenticatedAppLeadsIdRoute: AuthenticatedAppLeadsIdRoute,
  AuthenticatedAppQuotesIdRoute: AuthenticatedAppQuotesIdRoute,
  AuthenticatedAppQuotesCatalogRoute: AuthenticatedAppQuotesCatalogRoute,
  AuthenticatedAppActivitiesIndexRoute: AuthenticatedAppActivitiesIndexRoute,
  AuthenticatedAppAnalyticsIndexRoute: AuthenticatedAppAnalyticsIndexRoute,
  AuthenticatedAppCompaniesIndexRoute: AuthenticatedAppCompaniesIndexRoute,
  AuthenticatedAppContactsIndexRoute: AuthenticatedAppContactsIndexRoute,
  AuthenticatedAppDealsIndexRoute: AuthenticatedAppDealsIndexRoute,
  AuthenticatedAppInvoicesIndexRoute: AuthenticatedAppInvoicesIndexRoute,
  AuthenticatedAppLeadsIndexRoute: AuthenticatedAppLeadsIndexRoute,
  AuthenticatedAppPipelineIndexRoute: AuthenticatedAppPipelineIndexRoute,
  AuthenticatedAppQuotesIndexRoute: AuthenticatedAppQuotesIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppTasksIndexRoute: AuthenticatedAppTasksIndexRoute,
  AuthenticatedAppInvoicesPrintIdRoute: AuthenticatedAppInvoicesPrintIdRoute,
  AuthenticatedAppQuotesPrintIdRoute: AuthenticatedAppQuotesPrintIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MfaRoute: MfaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicLeadsCaptureRoute: ApiPublicLeadsCaptureRoute,
  ApiPublicLeadsCaptureSubmitRoute: ApiPublicLeadsCaptureSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
