// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const serverEnv = typeof process !== "undefined" ? process.env : {};
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  serverEnv.SUPABASE_URL ||
  "https://ncggjsjzjfgoceoszjhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  serverEnv.SUPABASE_PUBLISHABLE_KEY ||
  "sb_publishable_VO_1HPPNw-Y-nGVHLEdK8g_6Dkwq6zV";
const LOCAL_PREVIEW_KEY = "tally-crm-local-preview";

export function isSupabaseConfigured() {
  return Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}

export function missingSupabaseConfigMessage() {
  const missing = [
    ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
    ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
  ];
  return `Missing Supabase environment variable(s): ${missing.join(
    ", ",
  )}. Connect Supabase in Lovable Cloud or add local Vite env vars.`;
}

export function isLocalPreviewEnabled() {
  if (typeof window === "undefined") return false;
  return window.localStorage.getItem(LOCAL_PREVIEW_KEY) === "true";
}

export function enableLocalPreview() {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(LOCAL_PREVIEW_KEY, "true");
}

export function disableLocalPreview() {
  if (typeof window === "undefined") return;
  window.localStorage.removeItem(LOCAL_PREVIEW_KEY);
}

function createSupabaseClient() {
  if (!isSupabaseConfigured()) {
    console.warn(`[Supabase] ${missingSupabaseConfigMessage()} Using local demo client.`);
    return createDemoSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

function createDemoSupabaseClient() {
  const emptyListResponse = { data: [], error: null, count: 0, status: 200, statusText: "OK" };
  const emptyObjectResponse: typeof emptyListResponse = {
    data: [] as never[],
    error: null,
    count: 0,
    status: 200,
    statusText: "OK",
  };

  function builder(response: typeof emptyListResponse = emptyListResponse): unknown {
    return new Proxy(
      {
        then: (resolve: (value: typeof response) => void, reject?: (reason: unknown) => void) =>
          Promise.resolve(response).then(resolve, reject),
      },
      {
        get(target, prop) {
          if (prop === "then") return target.then;
          if (prop === "single" || prop === "maybeSingle")
            return () => builder(emptyObjectResponse);
          if (prop === "select" || prop === "insert" || prop === "update" || prop === "upsert") {
            return () => builder(response);
          }
          if (prop === "delete") return () => builder(emptyObjectResponse);
          return () => builder(response);
        },
      },
    );
  }

  return {
    auth: {
      getUser: async () => ({ data: { user: null }, error: null }),
      getSession: async () => ({ data: { session: null }, error: null }),
      getClaims: async () => ({ data: { claims: null }, error: null }),
      mfa: {
        getAuthenticatorAssuranceLevel: async () => ({
          data: { currentLevel: "aal1", nextLevel: "aal1", currentAuthenticationMethods: [] },
          error: null,
        }),
        listFactors: async () => ({ data: { all: [], totp: [] }, error: null }),
        enroll: async () => ({ data: null, error: new Error(missingSupabaseConfigMessage()) }),
        challenge: async () => ({ data: null, error: new Error(missingSupabaseConfigMessage()) }),
        verify: async () => ({ data: null, error: new Error(missingSupabaseConfigMessage()) }),
        unenroll: async () => ({ data: null, error: null }),
      },
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: new Error(missingSupabaseConfigMessage()),
      }),
      resetPasswordForEmail: async () => ({
        data: null,
        error: new Error(missingSupabaseConfigMessage()),
      }),
      updateUser: async () => ({
        data: { user: null },
        error: new Error(missingSupabaseConfigMessage()),
      }),
      signOut: async () => ({ error: null }),
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => undefined,
          },
        },
      }),
    },
    from: () => builder(),
  } as unknown as ReturnType<typeof createClient<Database>>;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
